export enum PermissionMessage {
	CREATE_SUCCESS = '创建权限成功',
	CREATE_ERROR = '创建权限失败',
	UPDATE_SUCCESS = '更新权限成功',
	UPDATE_ERROR = '更新权限失败',
	DELETE_SUCCESS = '删除权限成功',
	DELETE_ERROR = '删除权限失败',
	GET_DETAIL_SUCCESS = '获取权限详情成功',
	GET_DETAIL_ERROR = '获取权限详情失败',
	GET_LIST_SUCCESS = '获取权限列表成功',
	GET_LIST_ERROR = '获取权限列表失败',
	NOT_EXIST = '权限不存在',
	CODE_EXISTS = '权限码已存在',
	INVALID_PARAMS = '无效的参数',
	NAME_REQUIRED = '权限名称不能为空',
	CODE_REQUIRED = '权限码不能为空',
	INVALID_STATUS = '无效的状态值',
	GET_ALL_SUCCESS = '获取全部权限成功',
	GET_ALL_ERROR = '获取全部权限失败',
	UPDATE_STATUS_SUCCESS = '更新权限状态成功',
	UPDATE_STATUS_ERROR = '更新权限状态失败'
}
