name: Deploy

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '18.x'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PWD: ${{ secrets.MYSQL_PWD }}
          APP_PORT: ${{ secrets.APP_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AES_KEY: ${{ secrets.AES_KEY }}
          AES_IV: ${{ secrets.AES_IV }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

      # 部署到 GitHub 仓库
      - name: Push to koa-server repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'flow-zy'
          destination-repository-name: 'koa-server'
          user-email: ${{ secrets.USER_EMAIL }}
          target-branch: main

      # 设置 PM2 配置文件
      - name: Create PM2 config
        run: |
          echo '{
            "apps": [{
              "name": "rac-admin",
              "script": "dist/app.js",
              "instances": 2,
              "exec_mode": "cluster",
              "env_production": {
                "NODE_ENV": "production",
                "MYSQL_DB": "${{ secrets.MYSQL_DB }}",
                "MYSQL_HOST": "${{ secrets.MYSQL_HOST }}",
                "MYSQL_USER": "${{ secrets.MYSQL_USER }}",
                "MYSQL_PWD": "${{ secrets.MYSQL_PWD }}",
                "APP_PORT": "${{ secrets.APP_PORT }}",
                "JWT_SECRET": "${{ secrets.JWT_SECRET }}",
                "AES_KEY": "${{ secrets.AES_KEY }}",
                "AES_IV": "${{ secrets.AES_IV }}",
                "REDIS_HOST": "${{ secrets.REDIS_HOST }}",
                "REDIS_PORT": "${{ secrets.REDIS_PORT }}",
                "REDIS_PASSWORD": "${{ secrets.REDIS_PASSWORD }}"
              }
            }]
          }' > ecosystem.config.json

      # 启动应用
      - name: Start application
        run: |
          npm install pm2 -g
          pm2 start ecosystem.config.json --env production